apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: garment-${ENVIRONMENT}
data:
  NODE_ENV: "${ENVIRONMENT}"
  PORT: "3000"
  LOG_LEVEL: "info"
  UPLOAD_LIMIT: "10MB"
  ALLOWED_FILE_TYPES: "jpg,jpeg,png,gif"