apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: garment-${ENVIRONMENT}
type: Opaque
data:
  host: # Base64 encoded database host
  database: # Base64 encoded database name
  username: # Base64 encoded database username
  password: # Base64 encoded database password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: garment-${ENVIRONMENT}
type: Opaque
data:
  url: # Base64 encoded Redis URL
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: garment-${ENVIRONMENT}
type: Opaque
data:
  jwt-secret: # Base64 encoded JWT secret