apiVersion: apps/v1
kind: Deployment
metadata:
  name: garment-admin
  namespace: garment-${ENVIRONMENT}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: garment-admin
  template:
    metadata:
      labels:
        app: garment-admin
    spec:
      containers:
      - name: garment-admin
        image: kumarbhakta81/garment-admin:${IMAGE_TAG}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5