name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name garment-staging-cluster
      
      - name: Deploy Backend
        run: |
          kubectl set image deployment/garment-backend garment-backend=kumarbhakta81/garment-backend:${{ github.sha }} -n garment-staging
          kubectl rollout status deployment/garment-backend -n garment-staging --timeout=600s
      
      - name: Deploy Frontend
        run: |
          kubectl set image deployment/garment-admin garment-admin=kumarbhakta81/garment-admin:${{ github.sha }} -n garment-staging
          kubectl rollout status deployment/garment-admin -n garment-staging --timeout=600s
      
      - name: Run Health Checks
        run: ./deploy/scripts/health-check.sh staging
      
      - name: Setup Node.js for Integration Tests
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies for Integration Tests
        run: |
          npm ci
      
      - name: Run Integration Tests
        run: |
          npm run test:integration:staging
        env:
          STAGING_API_URL: https://api-staging.garmentplatform.com