name: CI Pipeline (Simplified)

on:
  push:
    branches: [ main, develop, staging ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Backend Build and Test
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install Backend Dependencies
        run: |
          cd server
          npm ci
      
      - name: Run Backend Linting
        run: |
          cd server
          npm run lint
      
      - name: Run Backend Tests
        run: |
          cd server
          npm test
      
      - name: Check Backend Start
        run: |
          cd server
          timeout 10s npm start || exit 0

  # Frontend Build and Test  
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install Frontend Dependencies
        run: |
          cd client
          npm ci
      
      - name: Run Frontend Linting
        run: |
          cd client
          npm run lint
      
      - name: Run Frontend Tests
        run: |
          cd client
          npm test -- --passWithNoTests --watchAll=false
      
      - name: Build Frontend
        run: |
          cd client
          npm run build

  # Basic Code Quality (without external services)
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          cd server && npm ci
          cd ../client && npm ci
      
      - name: Run Prettier Check
        run: |
          cd server && npm run format:check
          cd ../client && npm run format:check